### ISSUE TITLE
how to change { to {{

### ISSUE THREAD

**Issue by zerosoul** [ecomfe/smarty4js#11]
I want to change the single bracket to double for wrapping code,is it possible?

**Comment by zoumiaojiang** [comment]
if use API

```javascript
var smarty = new Smarty(); 
smarty.config({
    'left_delimiter':  '{{', 
    'right_delimiter': '}}'
});
```

before compile the template code; 

also you can put those options to a config file like `config.js`
then use command like`smarty4js compile sometemplate.tpl --config=./pathofconfig/config.js`

**Comment by zerosoul** [comment]
thanks
